import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://www.epgglobalone.com/en",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 1,
      alternates: { languages: { en: "https://www.epgglobalone.com/en", es: "https://www.epgglobalone.com/es", ru: "https://www.epgglobalone.com/ru" } },
    },
    {
      url: "https://www.epgglobalone.com/es",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 1,
      alternates: { languages: { en: "https://www.epgglobalone.com/en", es: "https://www.epgglobalone.com/es", ru: "https://www.epgglobalone.com/ru" } },
    },
    {
      url: "https://www.epgglobalone.com/ru",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 1,
      alternates: { languages: { en: "https://www.epgglobalone.com/en", es: "https://www.epgglobalone.com/es", ru: "https://www.epgglobalone.com/ru" } },
    },
    {
      url: "https://www.epgglobalone.com/en/pricing",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/pricing", es: "https://www.epgglobalone.com/es/precios", ru: "https://www.epgglobalone.com/ru/ceny" } },
    },
    {
      url: "https://www.epgglobalone.com/es/precios",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/pricing", es: "https://www.epgglobalone.com/es/precios", ru: "https://www.epgglobalone.com/ru/ceny" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/ceny",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/pricing", es: "https://www.epgglobalone.com/es/precios", ru: "https://www.epgglobalone.com/ru/ceny" } },
    },
    {
      url: "https://www.epgglobalone.com/en/partners",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/partners", es: "https://www.epgglobalone.com/es/socios", ru: "https://www.epgglobalone.com/ru/partners" } },
    },
    {
      url: "https://www.epgglobalone.com/es/socios",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/partners", es: "https://www.epgglobalone.com/es/socios", ru: "https://www.epgglobalone.com/ru/partners" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/partners",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/partners", es: "https://www.epgglobalone.com/es/socios", ru: "https://www.epgglobalone.com/ru/partners" } },
    },
    {
      url: "https://www.epgglobalone.com/en/research",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/research", es: "https://www.epgglobalone.com/es/investigacion", ru: "https://www.epgglobalone.com/ru/issledovanie" } },
    },
    {
      url: "https://www.epgglobalone.com/es/investigacion",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/research", es: "https://www.epgglobalone.com/es/investigacion", ru: "https://www.epgglobalone.com/ru/issledovanie" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/issledovanie",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/research", es: "https://www.epgglobalone.com/es/investigacion", ru: "https://www.epgglobalone.com/ru/issledovanie" } },
    },
    {
      url: "https://www.epgglobalone.com/en/trust-score",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/trust-score", es: "https://www.epgglobalone.com/es/indice-de-confianza", ru: "https://www.epgglobalone.com/ru/reiting" } },
    },
    {
      url: "https://www.epgglobalone.com/es/indice-de-confianza",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/trust-score", es: "https://www.epgglobalone.com/es/indice-de-confianza", ru: "https://www.epgglobalone.com/ru/reiting" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/reiting",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/trust-score", es: "https://www.epgglobalone.com/es/indice-de-confianza", ru: "https://www.epgglobalone.com/ru/reiting" } },
    },
    {
      url: "https://www.epgglobalone.com/en/terms",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/terms", es: "https://www.epgglobalone.com/es/terminos", ru: "https://www.epgglobalone.com/ru/usloviya" } },
    },
    {
      url: "https://www.epgglobalone.com/es/terminos",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/terms", es: "https://www.epgglobalone.com/es/terminos", ru: "https://www.epgglobalone.com/ru/usloviya" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/usloviya",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/terms", es: "https://www.epgglobalone.com/es/terminos", ru: "https://www.epgglobalone.com/ru/usloviya" } },
    },
    {
      url: "https://www.epgglobalone.com/en/privacy",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/privacy", es: "https://www.epgglobalone.com/es/privacidad", ru: "https://www.epgglobalone.com/ru/konfidencialnost" } },
    },
    {
      url: "https://www.epgglobalone.com/es/privacidad",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/privacy", es: "https://www.epgglobalone.com/es/privacidad", ru: "https://www.epgglobalone.com/ru/konfidencialnost" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/konfidencialnost",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/privacy", es: "https://www.epgglobalone.com/es/privacidad", ru: "https://www.epgglobalone.com/ru/konfidencialnost" } },
    },
    {
      url: "https://www.epgglobalone.com/ru/voprosy",
      lastModified: new Date("2026-10-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/o-kompanii",
      lastModified: new Date("2026-10-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/otrasli",
      lastModified: new Date("2026-10-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/obrazcy",
      lastModified: new Date("2026-10-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/issledovaniya",
      lastModified: new Date("2026-10-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/llm-info",
      lastModified: new Date("2026-10-08"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: "https://www.epgglobalone.com/ru/otrasli/kliniki",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/otrasli/oteli",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/otrasli/turizm",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/otrasli/zastrojshchiki",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/ru/otrasli/mezhdunarodnye",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.epgglobalone.com/en/industries/clinics",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/clinics", es: "https://www.epgglobalone.com/es/sectores/clinicas", ru: "https://www.epgglobalone.com/ru/otrasli/kliniki" } },
    },
    {
      url: "https://www.epgglobalone.com/en/industries/hotels",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/hotels", es: "https://www.epgglobalone.com/es/sectores/hoteles", ru: "https://www.epgglobalone.com/ru/otrasli/oteli" } },
    },
    {
      url: "https://www.epgglobalone.com/en/industries/tourism-boards",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/tourism-boards", es: "https://www.epgglobalone.com/es/sectores/organismos-de-turismo", ru: "https://www.epgglobalone.com/ru/otrasli/turizm" } },
    },
    {
      url: "https://www.epgglobalone.com/en/industries/real-estate-developers",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/real-estate-developers", es: "https://www.epgglobalone.com/es/sectores/desarrolladoras-inmobiliarias", ru: "https://www.epgglobalone.com/ru/otrasli/zastrojshchiki" } },
    },
    {
      url: "https://www.epgglobalone.com/en/industries/international-companies",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/international-companies", es: "https://www.epgglobalone.com/es/sectores/empresas-internacionales", ru: "https://www.epgglobalone.com/ru/otrasli/mezhdunarodnye" } },
    },
    {
      url: "https://www.epgglobalone.com/es/sectores/clinicas",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/clinics", es: "https://www.epgglobalone.com/es/sectores/clinicas", ru: "https://www.epgglobalone.com/ru/otrasli/kliniki" } },
    },
    {
      url: "https://www.epgglobalone.com/es/sectores/hoteles",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/hotels", es: "https://www.epgglobalone.com/es/sectores/hoteles", ru: "https://www.epgglobalone.com/ru/otrasli/oteli" } },
    },
    {
      url: "https://www.epgglobalone.com/es/sectores/organismos-de-turismo",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/tourism-boards", es: "https://www.epgglobalone.com/es/sectores/organismos-de-turismo", ru: "https://www.epgglobalone.com/ru/otrasli/turizm" } },
    },
    {
      url: "https://www.epgglobalone.com/es/sectores/desarrolladoras-inmobiliarias",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/real-estate-developers", es: "https://www.epgglobalone.com/es/sectores/desarrolladoras-inmobiliarias", ru: "https://www.epgglobalone.com/ru/otrasli/zastrojshchiki" } },
    },
    {
      url: "https://www.epgglobalone.com/es/sectores/empresas-internacionales",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries/international-companies", es: "https://www.epgglobalone.com/es/sectores/empresas-internacionales", ru: "https://www.epgglobalone.com/ru/otrasli/mezhdunarodnye" } },
    },
    {
      url: "https://www.epgglobalone.com/en/about",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/about", es: "https://www.epgglobalone.com/es/acerca-de", ru: "https://www.epgglobalone.com/ru/o-kompanii" } },
    },
    {
      url: "https://www.epgglobalone.com/es/acerca-de",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/about", es: "https://www.epgglobalone.com/es/acerca-de", ru: "https://www.epgglobalone.com/ru/o-kompanii" } },
    },
    {
      url: "https://www.epgglobalone.com/en/industries",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries", es: "https://www.epgglobalone.com/es/sectores", ru: "https://www.epgglobalone.com/ru/otrasli" } },
    },
    {
      url: "https://www.epgglobalone.com/es/sectores",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/industries", es: "https://www.epgglobalone.com/es/sectores", ru: "https://www.epgglobalone.com/ru/otrasli" } },
    },
    {
      url: "https://www.epgglobalone.com/en/samples",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/samples", es: "https://www.epgglobalone.com/es/muestras", ru: "https://www.epgglobalone.com/ru/obrazcy" } },
    },
    {
      url: "https://www.epgglobalone.com/es/muestras",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/samples", es: "https://www.epgglobalone.com/es/muestras", ru: "https://www.epgglobalone.com/ru/obrazcy" } },
    },
    {
      url: "https://www.epgglobalone.com/en/website-trust-research",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/website-trust-research", es: "https://www.epgglobalone.com/es/investigaciones-sobre-confianza", ru: "https://www.epgglobalone.com/ru/issledovaniya" } },
    },
    {
      url: "https://www.epgglobalone.com/es/investigaciones-sobre-confianza",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/website-trust-research", es: "https://www.epgglobalone.com/es/investigaciones-sobre-confianza", ru: "https://www.epgglobalone.com/ru/issledovaniya" } },
    },
    {
      url: "https://www.epgglobalone.com/en/faq",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/faq", es: "https://www.epgglobalone.com/es/preguntas-frecuentes", ru: "https://www.epgglobalone.com/ru/voprosy" } },
    },
    {
      url: "https://www.epgglobalone.com/es/preguntas-frecuentes",
      lastModified: new Date("2026-10-09"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://www.epgglobalone.com/en/faq", es: "https://www.epgglobalone.com/es/preguntas-frecuentes", ru: "https://www.epgglobalone.com/ru/voprosy" } },
    },
  ];
}
