import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://epgglobalone.com/en",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 1,
      alternates: { languages: { en: "https://epgglobalone.com/en", es: "https://epgglobalone.com/es", ru: "https://epgglobalone.com/ru" } },
    },
    {
      url: "https://epgglobalone.com/es",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 1,
      alternates: { languages: { en: "https://epgglobalone.com/en", es: "https://epgglobalone.com/es", ru: "https://epgglobalone.com/ru" } },
    },
    {
      url: "https://epgglobalone.com/ru",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 1,
      alternates: { languages: { en: "https://epgglobalone.com/en", es: "https://epgglobalone.com/es", ru: "https://epgglobalone.com/ru" } },
    },
    {
      url: "https://epgglobalone.com/en/pricing",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/pricing", es: "https://epgglobalone.com/es/precios", ru: "https://epgglobalone.com/ru/ceny" } },
    },
    {
      url: "https://epgglobalone.com/es/precios",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/pricing", es: "https://epgglobalone.com/es/precios", ru: "https://epgglobalone.com/ru/ceny" } },
    },
    {
      url: "https://epgglobalone.com/ru/ceny",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/pricing", es: "https://epgglobalone.com/es/precios", ru: "https://epgglobalone.com/ru/ceny" } },
    },
    {
      url: "https://epgglobalone.com/en/partners",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://epgglobalone.com/en/partners", es: "https://epgglobalone.com/es/socios", ru: "https://epgglobalone.com/ru/partners" } },
    },
    {
      url: "https://epgglobalone.com/es/socios",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://epgglobalone.com/en/partners", es: "https://epgglobalone.com/es/socios", ru: "https://epgglobalone.com/ru/partners" } },
    },
    {
      url: "https://epgglobalone.com/ru/partners",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.8,
      alternates: { languages: { en: "https://epgglobalone.com/en/partners", es: "https://epgglobalone.com/es/socios", ru: "https://epgglobalone.com/ru/partners" } },
    },
    {
      url: "https://epgglobalone.com/en/research",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/research", es: "https://epgglobalone.com/es/investigacion", ru: "https://epgglobalone.com/ru/issledovanie" } },
    },
    {
      url: "https://epgglobalone.com/es/investigacion",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/research", es: "https://epgglobalone.com/es/investigacion", ru: "https://epgglobalone.com/ru/issledovanie" } },
    },
    {
      url: "https://epgglobalone.com/ru/issledovanie",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/research", es: "https://epgglobalone.com/es/investigacion", ru: "https://epgglobalone.com/ru/issledovanie" } },
    },
    {
      url: "https://epgglobalone.com/en/trust-score",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/trust-score", es: "https://epgglobalone.com/es/indice-de-confianza", ru: "https://epgglobalone.com/ru/reiting" } },
    },
    {
      url: "https://epgglobalone.com/es/indice-de-confianza",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/trust-score", es: "https://epgglobalone.com/es/indice-de-confianza", ru: "https://epgglobalone.com/ru/reiting" } },
    },
    {
      url: "https://epgglobalone.com/ru/reiting",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "monthly",
      priority: 0.9,
      alternates: { languages: { en: "https://epgglobalone.com/en/trust-score", es: "https://epgglobalone.com/es/indice-de-confianza", ru: "https://epgglobalone.com/ru/reiting" } },
    },
    {
      url: "https://epgglobalone.com/en/terms",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://epgglobalone.com/en/terms", es: "https://epgglobalone.com/es/terminos", ru: "https://epgglobalone.com/ru/usloviya" } },
    },
    {
      url: "https://epgglobalone.com/es/terminos",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://epgglobalone.com/en/terms", es: "https://epgglobalone.com/es/terminos", ru: "https://epgglobalone.com/ru/usloviya" } },
    },
    {
      url: "https://epgglobalone.com/ru/usloviya",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://epgglobalone.com/en/terms", es: "https://epgglobalone.com/es/terminos", ru: "https://epgglobalone.com/ru/usloviya" } },
    },
    {
      url: "https://epgglobalone.com/en/privacy",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://epgglobalone.com/en/privacy", es: "https://epgglobalone.com/es/privacidad", ru: "https://epgglobalone.com/ru/konfidencialnost" } },
    },
    {
      url: "https://epgglobalone.com/es/privacidad",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://epgglobalone.com/en/privacy", es: "https://epgglobalone.com/es/privacidad", ru: "https://epgglobalone.com/ru/konfidencialnost" } },
    },
    {
      url: "https://epgglobalone.com/ru/konfidencialnost",
      lastModified: new Date("2026-10-07"),
      changeFrequency: "yearly",
      priority: 0.3,
      alternates: { languages: { en: "https://epgglobalone.com/en/privacy", es: "https://epgglobalone.com/es/privacidad", ru: "https://epgglobalone.com/ru/konfidencialnost" } },
    },
  ];
}
